<?php
@include("../../inc/header.php");

/*
		SoftName : EmpireBak
		Author   : wm_chief
		Copyright: Powered by www.phome.net
*/

E_D("DROP TABLE IF EXISTS `www_92game_net_ecms_infoclass_photo`;");
E_C("CREATE TABLE `www_92game_net_ecms_infoclass_photo` (
  `classid` int(10) unsigned NOT NULL DEFAULT '0',
  `zz_title` text NOT NULL,
  `z_title` varchar(255) NOT NULL DEFAULT '',
  `qz_title` varchar(255) NOT NULL DEFAULT '',
  `save_title` varchar(10) NOT NULL DEFAULT '',
  `zz_titlepic` text NOT NULL,
  `z_titlepic` varchar(255) NOT NULL DEFAULT '',
  `qz_titlepic` varchar(255) NOT NULL DEFAULT '',
  `save_titlepic` varchar(10) NOT NULL DEFAULT '',
  `zz_newstime` text NOT NULL,
  `z_newstime` varchar(255) NOT NULL DEFAULT '',
  `qz_newstime` varchar(255) NOT NULL DEFAULT '',
  `save_newstime` varchar(10) NOT NULL DEFAULT '',
  `zz_filesize` text NOT NULL,
  `z_filesize` varchar(255) NOT NULL DEFAULT '',
  `qz_filesize` varchar(255) NOT NULL DEFAULT '',
  `save_filesize` varchar(10) NOT NULL DEFAULT '',
  `zz_picsize` text NOT NULL,
  `z_picsize` varchar(255) NOT NULL DEFAULT '',
  `qz_picsize` varchar(255) NOT NULL DEFAULT '',
  `save_picsize` varchar(10) NOT NULL DEFAULT '',
  `zz_picfbl` text NOT NULL,
  `z_picfbl` varchar(255) NOT NULL DEFAULT '',
  `qz_picfbl` varchar(255) NOT NULL DEFAULT '',
  `save_picfbl` varchar(10) NOT NULL DEFAULT '',
  `zz_picfrom` text NOT NULL,
  `z_picfrom` varchar(255) NOT NULL DEFAULT '',
  `qz_picfrom` varchar(255) NOT NULL DEFAULT '',
  `save_picfrom` varchar(10) NOT NULL DEFAULT '',
  `zz_picurl` text NOT NULL,
  `z_picurl` varchar(255) NOT NULL DEFAULT '',
  `qz_picurl` varchar(255) NOT NULL DEFAULT '',
  `save_picurl` varchar(10) NOT NULL DEFAULT '',
  `zz_morepic` text NOT NULL,
  `z_morepic` varchar(255) NOT NULL DEFAULT '',
  `qz_morepic` varchar(255) NOT NULL DEFAULT '',
  `save_morepic` varchar(10) NOT NULL DEFAULT '',
  `zz_num` text NOT NULL,
  `z_num` varchar(255) NOT NULL DEFAULT '',
  `qz_num` varchar(255) NOT NULL DEFAULT '',
  `save_num` varchar(10) NOT NULL DEFAULT '',
  `zz_width` text NOT NULL,
  `z_width` varchar(255) NOT NULL DEFAULT '',
  `qz_width` varchar(255) NOT NULL DEFAULT '',
  `save_width` varchar(10) NOT NULL DEFAULT '',
  `zz_height` text NOT NULL,
  `z_height` varchar(255) NOT NULL DEFAULT '',
  `qz_height` varchar(255) NOT NULL DEFAULT '',
  `save_height` varchar(10) NOT NULL DEFAULT '',
  `zz_picsay` text NOT NULL,
  `z_picsay` varchar(255) NOT NULL DEFAULT '',
  `qz_picsay` varchar(255) NOT NULL DEFAULT '',
  `save_picsay` varchar(10) NOT NULL DEFAULT '',
  `zz_cid` text NOT NULL,
  `z_cid` varchar(255) NOT NULL,
  `qz_cid` varchar(255) NOT NULL,
  `save_cid` varchar(10) NOT NULL,
  `zz_hdpic` text NOT NULL,
  `z_hdpic` varchar(255) NOT NULL,
  `qz_hdpic` varchar(255) NOT NULL,
  `save_hdpic` varchar(10) NOT NULL,
  `zz_gxhd` text NOT NULL,
  `z_gxhd` varchar(255) NOT NULL,
  `qz_gxhd` varchar(255) NOT NULL,
  `save_gxhd` varchar(10) NOT NULL,
  `zz_re1` text NOT NULL,
  `z_re1` varchar(255) NOT NULL,
  `qz_re1` varchar(255) NOT NULL,
  `save_re1` varchar(10) NOT NULL,
  `zz_re2` text NOT NULL,
  `z_re2` varchar(255) NOT NULL,
  `qz_re2` varchar(255) NOT NULL,
  `save_re2` varchar(10) NOT NULL,
  `zz_pdhd` text NOT NULL,
  `z_pdhd` varchar(255) NOT NULL,
  `qz_pdhd` varchar(255) NOT NULL,
  `save_pdhd` varchar(10) NOT NULL,
  `zz_indexhd` text NOT NULL,
  `z_indexhd` varchar(255) NOT NULL,
  `qz_indexhd` varchar(255) NOT NULL,
  `save_indexhd` varchar(10) NOT NULL,
  `zz_indextj` text NOT NULL,
  `z_indextj` varchar(255) NOT NULL,
  `qz_indextj` varchar(255) NOT NULL,
  `save_indextj` varchar(10) NOT NULL,
  PRIMARY KEY (`classid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8");

@include("../../inc/footer.php");
?>